### ISSUE TITLE
Cleanup of btrbk archive source snapshots

### ISSUE THREAD

**Issue by emlove** [digint/btrbk#101]
In my current setup, I have an always-on nas server, and a laptop. I have a btrbk instance on the laptop that pushes backup images to the server. I then periodically use `btrbk archive` to copy the images to an external offline hard drive.

In this workflow, `snapshot_preserve` rules will delete old images on my laptop after they have been used to send an incremental update to the server. I've defined `archive_preserve` rules which clear old images from the external disk, but as I can see there isn't a way to clear old images from the server. I could modify the laptop btrbk instance with `target_preserve` rules, but this could potentially delete the last common parent of the external disk.

I think to achieve what I'm looking to do, I would need an `archive_source_preserve` setting.

For what I'm trying to achieve, I only want to store the latest snapshots, so applying the cleanup rules in the correct order is necessary. There won't be a several month safety window.

**Comment by digint** [comment]
I'm aware of this problem, but have not come up with any satisfying solution yet. `btrbk archive` relies on a decent safety window for now, that's one reason why it's still flagged "experimental".

Unfortunately, adding an `archive_source_preserve` option would be dangerous, as this could potentially delete common snapshot/backup pairs. You could then argue that btrbk should also check for those pairs, but this is not really possible as the `btrbk archive` command is designed to work without a configuration, being very useful to sync backup/archive disks offline.

**The only way I see to really solve this problem is the following** (which would satisfy your setup I believe):

1. Add a mechanism to prevent "latest common (source snapshot as well as archive)" subvolumes to be deleted.
2. Add an command/option to manually "delete all backup subvolumes except the common ones", which would be run after all archive disks are updated.

This could be achieved by introducing "delete-prevention-lock-files", e.g. `<name>.<timestamp>.lock.<lock-id>`, with `<lock-id>` being the uuid of the archive disk.

Actually, I don't really like that because it adds a lot of complexity (and confusion) as well as possible stale locks (e.g. from old archive disks).

**To solve your problem with the current btrbk version**, this is what you could do after `btrbk archive`:

1. manually rename the backup subvolume you want to keep for later archives (btrbk will never delete subvolumes which do not match its naming scheme, but still use them as send/receive parents): e.g. `mv subvol-YYYYMMDD subvol-YYYYMMDD.locked`
2. clean your backups subvolumes using something like this: `btrbk run --override=target_preserve=no --override=target_preserve_min=latest`

This should work, but is not very satisfying I have to admit...

**Comment by armills** [comment]
That's understandable.

For now I'll just come up with a workaround in my own script, since it's such a simple case.

**Comment by kolcon** [comment]
I also crated a pull request to add some default values for archive_preserve and archive_preserve_min to the example config file, to make it easier to find the options.
