### ISSUE TITLE
Add support for adopting existing backup subvolume

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#102]
I have a big subvolume I'm backing up. For the initial backup, doing a cp -ar to an nfs mount is about 5 times faster than doing a btrfs send (5 days vs 1 day). And, after that I can also adopt the efficiency of btrfs send for the incremental changes on top of the existing backup once it's perfectly in sync. This also works if I've been using some other method like rsync for incremental changes. However, btrbk does not support doing this, as it always wants to start with a full copy with the slow btrfs send, and it's not worth doing 5 day send, or making space required to do a separate full backup.

Maybe it's possible by naming things a certain way, but I didn't see how in the docs, and figured it might just be easier to write my own script to use btrfs send. note: I noticed this probably a year ago and have been meaning to send a note as feedback, so let me know if things have changed.

**Comment by digint** [comment]
A little sidenote first: while `cp -ar` or `rsync` might be faster than `btrfs send/receive`, they both don't take cloned content into account (e.g. a source file created with `cp --reflink` would use twice the size on the rsync target).

Now if I understand you correctly, what you are trying to do is:

1. make initial backup using `cp -ar` or `rsync` from `<source_subvolume>` to `<target_subvolume>` (making sure the are "perfectly in sync")
2. make a read-only snapshot out of `<target_subvolume>`
3. use `<target_subvolume>` as parent for subsequent incremantal send/receive

While this might work in theory, you'll have to manually set the `received_uuid` on `<target_subvolume>` to the uuid of the source subvolume, so that subsequent `btrfs send -p <source_subvolume> | btrfs receive` recognizes it. This might be doable, but actually I don't know of any ioctl (or other ways) to achive this.

If I read your post correctly, you already managed to do something like this? Or are you just asking if this is possible?

**Comment by ian-kelling** [comment]
Ahh, yes, you are right. I tested this a while ago, but I didn't pay close enough attention. What you can do currently is to create a recieved subvol, then make the origin and recieved volumes be rw, add to the origin subvolume, sync the recieved on outside of btrfs (ie. cp -ar), then have a different subvol with newer changes do a btrfs send -p in reference to those previous ones. But this needs new subvolumes volumes, as you've pointed out. So I wouldn't expect btrbk to have a feature related to this (and, perhaps it will won't work if there are reflinked files). I will ask btrfs mailing list about the possibility of setting received_uuid.

**Comment by ian-kelling** [comment]
I'm seeing btrfstune -U which seems like it could work with btrbk. Still, same conclusion to keep this closed, having to do some things manually is fine.

**Comment by ian-kelling** [comment]
In case anyone runs into this. btrfstune -U is no help. You can get btrfs send to use existing subvols by starting with an empty send and then copying into the subvolumes, which works perfectly for small test subvols, but on one with lots of files, the subsequent incremental send does not work incrementally for the most part, I canceled before it finished.

I figured out that I could get much better perf on the initial backup by doing a send to a file on an nfs share, then a receive from the file on the remote system. Then I renamed the subvols to fit with the btrbk naming scheme I was using and everything works fine.
