### ISSUE TITLE
Howto incremental + full backup

### ISSUE THREAD

**Issue by EvaSDK** [digint/btrbk#132]
I have been playing with btrbk for a while but could not manage to produce a working setup of say a monthly full backup with incremental snapshots based on that monthly backup. Is there any way to do this with btrbk at all ?

**Comment by digint** [comment]
I'm not sure what you are trying to achieve here, I don't see the point of making full backups when incremental is possible.

But maybe there is a point, so what you could do is running `btrbk --override=incremental=no run` once a month, and then every subsequent calls to btrbk should result in using the full backups.

**Comment by EvaSDK** [comment]
The point is to limit the consequences of a damaged incremental backup file as pointed in the man page. If I have a periodic full backup as well, in the worst case the damages are limited up to that full backup. It would be nice to be able to write this in the configuration file but having a command line override is good enough for me for the moment.

**Comment by digint** [comment]
Ah I see, so you are talking about "raw" backups. This issue is one of the points why raw backups still have the *experimental* flag on, and it's kind of hard to implement some "monthly non-incremental rotation" without a command-line argument. The problem is that btrbk is stateless, so it can not really know when to trigger a full backup. Maybe some kind of: "hey, it's past first day of month, and last full backup is older than xy days, trigger full backup!"

**Comment by digint** [comment]
Added an "enhancement" issue #133 for this, hoping I'd get some free time to work on btrbk soon

**Comment by EvaSDK** [comment]
Thanks for considering :)
