### ISSUE TITLE
Not all snapshots are transferred to the target

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#144]
I have the following configuration: 

```
timestamp_format	long
snapshot_preserve_min       1h
snapshot_preserve          14d

target_preserve_min        no
target_preserve            20d 10w *m

snapshot_dir               snapshots

volume /mnt/erik
  subvolume rootfs
	target send-receive    /mnt/heybe/snapshots/rootfs
```

# Expected result is: 

1. Take a snapshot, place it in `/mnt/erik/snapshots/rootfs.YYYYmmDDTHHmm`
2. Send all snapshots matching with `/mnt/erik/snapshots/rootfs.*` to `/mnt/heybe/snapshots/rootfs` (assuming this is not a first snapshot, I expect only changes will be transferred) 

# Actual result is: 

1. A new snapshot is being taken with a proper name 
2. Nothing happens. 

If I delete all subvolumes in `/mnt/heybe/snapshots/rootfs/*` and rerun the above configuration, then 

1. A new snapshot is being taken
2. First two snapshots are transferred to the target. 

Here is the last status of relevant folders: 

```
$ ls /mnt/erik/snapshots/ -1
rootfs.20170429T2001
rootfs.20170430T0140
rootfs.20170430T1917
rootfs.20170430T2017

$ ls -1 /mnt/heybe/snapshots/rootfs/
rootfs.20170429T2001
rootfs.20170430T0140
```

**Comment by digint** [comment]
You have set `target_preserve_min no`. Quoting the man page: "If set to “no”, only the backups following the target_preserve policy are created."

And you have `target_preserve 20d 10w *m`. This means you want daily backups for 20 days back. Quoting man-page: "daily: Defines how many days back daily backups should be preserved. The **first backup of a day is considered a daily backup**".

Your first backup of 2017-04-30 is `rootfs.20170430T0140`, so that's the one which is transferred.

If you want the latest snapshot to always be transferred, use `target_preserve_min  latest`.

**Comment by ceremcem** [comment]
OK, changing `target_preserve_min no` to `target_preserve_min 1h` solved my problem. 

(Changing it to `target_preserve_min latest` causes ending up with only latest snapshots per day in the target location, which is not something I wanted.)
