### ISSUE TITLE
Ability to delete snapshots 

### ISSUE THREAD

**Issue by HaleTom** [digint/btrbk#173]
My disk became 100% full and I tried to delete some snapshots to recover space.

I needed `-r` to not create new snapshots (`ENOSPC`).

But then this would not delete any unneeded snapshots as per the retention policy.

Would you consider adding a `delete` operation to remove snapshots not needed as per the retention policy?

**Comment by digint** [comment]
Sounds useful, and should be quite easy to implement.

Maybe we should also distinguish between `delete snapshots` and `delete backups` (though I can't see a use case for this right now, if you want to thin out the targets, you probably simply adapt the target_preserve policy).

As a workaround, try something like this:

```
# btrbk --override=snapshot_preserve=no \
        --override=snapshot_preserve_min=latest \
        --override=snapshot_create=no \
        --print-schedule \
        dryrun
```

**Comment by Gatak** [comment]
Perhaps add an option to list the relative size (btrfs fi du -s <snapshot>) would be useful in situations like this?

**Comment by HaleTom** [comment]
Thanks for the command above. It just saved my bacon: allowing a balance to work which previously said ENOSPC.

**Comment by xenithorb** [comment]
There have been times when I wanted `-r` to also remove backups based on the configuration. The first time I tried that I got a message:
```
NOTE: Preserved all snapshots and backups (option -p or -r present)
```
Which surprised me. 

`-r` is really "No new snapshots, preserve backups and snapshots"

I guess that makes sense since the intended purpose is to send missing backups, that's fine. I did expect it to prune backups based on the config though. I suppose you could just simply use `run` in that instance, couldn't you, but it would create a new snapshot and backup which my not be needed. 

Kinda need a "resume missing backups and pune old backups" or "sync backups"

**Comment by digint** [comment]
> There have been times when I wanted -r to also remove backups based on the configuration
> [...]
> -r is really "No new snapshots, preserve backups and snapshots"

This has changed, now there is `btrbk snapshot` or `btrbk resume` (see #150, already implemented on master branch). It will be included in the upcoming v0.26.0 release.

I'll implement `btrbk prune [snapshots|backups]` soon, not sure though if pruning backups makes much sense (as the missing backups will be re-created as long as the corresponding snapshots are still around, and you probably never want to delete "all but latest backup").

**Comment by xenithorb** [comment]
For me, the argument is that prune would be more for the case where I readjust the configuration and just want to match what backups and snapshots are left over to that new configuration. Normally this is due to me learning the natural temporal boundaries that reveal themselves over time and usage patterns. It's nice to be able to control retention in days, weeks, etc but when you misappropriate and are constantly filling that up with your current configuration, it could be nice to adjust and then "resync" that so the snapshots and backup environment reflect that. I believe `run` currently does this, or at least I've been using it to do that, but it also creates a new snapshot/backup which is not necessary if you just want to remove some snapshots or backups, thus prune I think is a viable command.

**Comment by digint** [comment]
Agreed, this makes sense.

So this is what I came up with:

### Currently available commands (master branch):

|Command|Result|
|:----|:----|
|`btrbk run`| create snapshots, create backups, delete backups, delete snapshots|
|`btrbk run --preserve`| create snapshots, create backups|
|`btrbk run --preserve-snapshots`| create snapshots, create backups, delete backups|
|`btrbk run --preserve-backups`| create snapshots, create backups, delete snapshots|
|`btrbk snapshot`| create snapshots, delete snapshots|
|`btrbk snapshot --preserve`|create snapshots|
|`btrbk resume`|create backup, delete backups, delete snapshots|
|`btrbk resume --preserve`|create backup|
|`btrbk resume --preserve-snapshots`|create backup, delete backups|
|`btrbk resume --preserve-backups`|create backup, delete snapshots|

### New commands, to be implemented

|Command|Result|
|:----|:----|
|`btrbk prune`|delete snapshots, delete backups|
|`btrbk prune --preserve-snapshots`|delete backups|
|`btrbk prune --preserve-backups`|delete snapshots|
|`btrbk prune --wipe`|delete all but latest snapshots, delete backups|

### Alternative

|Command|Result|
|:----|:----|
|`btrbk prune`|delete snapshots (short for "prune snapshots")|
|`btrbk prune snapshots`|delete snapshots|
|`btrbk prune backups`|delete backups|
|`btrbk prune snapshots --wipe`|delete all but latest snapshots|
|~~`btrbk prune backups --wipe`~~|~~delete all but latest backups (does not make sense for me)~~|

**Comment by xenithorb** [comment]
Nice! Yeah I think that hits the spot :) 

+1 For "New commands" vs. "Alternative"

**Comment by digint** [comment]
That was an easy one: Implemented `btrbk prune` and `--wipe`: 5bdc3e527ba4a47ac0d07915a2aac047e5ece836, 2e974c1f4fd3e3ea82560a0813f10dc781945750

**Comment by digint** [comment]
included in btrbk-0.26.0

**Comment by Geremia** [comment]
What would be neat is if btrbk would delete automatically delete the oldest backups when the destination disk is full.

**Comment by HaleTom** [comment]
These are excellent improvements, thanks a bunch!
