### ISSUE TITLE
using an SSH binary outside of /sbin:/bin:/usr/sbin:/usr/bin

### ISSUE THREAD

**Issue by boerwastaken** [digint/btrbk#178]
Upon discovering that btrbk doesn't honor $PATH (and thus puts my ssh wrapper script out of order) I rummaged around to have it honor $PATH, but this runs foul of taint mode:

```Insecure $ENV{PATH} while running with -T switch at /usr/local/sbin/btrbk line 710.```

What's the most elegant way forward? Here's some alternatives, some better than others:

1. An extra cli argument for btrbk, declaring a path that will be prefixed to the currently hardcoded `/sbin:/bin:/usr/sbin:/usr/bin`. Could be useful as a place to put SSH wrappers, symlinks to custom compiled btrfs-utils-du-jour etc.
2. An extra cli argument for btrbk, declaring the path to the ssh binary (it would solve my immediate problem, but not the general case)
3. Disable taint mode and just honor $PATH ;-)
4. An extra cli argument for btrbk wherein an SSH config file can be specified (it would solve my immediate problem, but not the general case)
5. ???

**Comment by digint** [comment]
Yeah, well, perl taint mode... While this is a nice feature of perl, e.g. it disallows using variables (such as filenames from the config file) which were not validated in system() commands, it also treats $PATH as insecure (which inherently is, as perl cannot know who messed around with it). See http://perldoc.perl.org/perlsec.html.

Initially, I enabled taint mode (`#!/usr/bin/perl -T`) because btrbk needs root (or more precisely: `btrfs` command called by btrbk needs root for most operations), and I can provide at least some basic security against attack vectors like "config file altered" or "PATH altered".

Actually, I'm thinking of removing taint mode for a while now, and furthermore move btrbk to /usr/bin (instead of /usr/sbin as it is now), because:

1. There is now ways to run btrbk as user, e.g. by enabling `backend btrfs-progs-btrbk`, or `backend btrfs-progs-sudo`
2. I could allow some user-defined programs to run, e.g. post-backup hooks
3. Taint mode does not *really* give much security, as $PATH should be sane on most distros, and /etc/btrbk/btrbk.conf should be writable by root only anyways.

> What's the most elegant way forward?

Adding a cli argument or config variable for this is pretty ugly and confusing. Hardcoding $PATH has always been ugly and confusing, since the beginning of btrbk...

Guess I'll drop it.

Dear Followers/Watchers: what do you think about it?

**Comment by boerwastaken** [comment]
Remove taint mode and honor $PATH sounds great to me, solves my problem :-) 👍

**Comment by digint** [comment]
Taint mode has now been disabled by default: 571dae4428d12b1ebba56a36b9b43fca28449781

**Comment by digint** [comment]
> Taint mode has now been disabled by default: 571dae4

Forgotten issue, should be closed
