### ISSUE TITLE
Does this app protect our backups from data rot?

### ISSUE THREAD

**Issue by inf3rno** [digint/btrbk#195]
I chose BTRFS because it protects my files from data rot automatically if used with RAID. Is there a way to protect our backups too?

Let's assume we have incremental backup on a single HDD without RAID and a file is corrupted on it somehow. Is there a simple way to detect and fix it? Or will we have an error message only when our RAID is gone and we try to restore the data from backup?

**Comment by digint** [comment]
You can detect data corruption by using `btrfs scrub` regularly. If you don't do this, errors will only appear when restoring data (or more precisely: as soon as you try to read the corrupted file).

I recommend running `btrfs scrub` periodically on both filesystems. If a corruption is detected by scrubbing your RAID filesystem, it will be automatically fixed by btrfs.

**Comment by inf3rno** [comment]
@digint Thanks!
