### ISSUE TITLE
No real path provided by "btrfs subvolume show"

### ISSUE THREAD

**Issue by bk1285** [digint/btrbk#23]
Hi,

first of all: Thanks a lot for this great tool! I use it regularly to transfer snapshots to my usb-drive.

While doing so, I tried the following scenario:
  - Take a daily snapshot
  - Transfer all daily snapshots, whenever my usb-drive is attached (e.g. once per week)

To do so, I have these settings in my config file:
    snapshot_create_always     yes
    resume_missing             yes

Mount point of my usb-drive is /mnt/btrfs_bkp. But if I want to run the script without having the disk attached, it will fail, throwing the following error (since the path /mnt/btrfs_bkp exists, but does not contain a btrfs-filesystem):

    WARNING: No real path provided by "btrfs subvolume show" for subvolume "/mnt/btrfs_bkp", using: /mnt/btrfs_bkp

    ERROR: process died unexpectedly (btrbk v0.17.0)
    Please contact the author: *********
    Stack Trace:
    ----------------------------------------
    Use of uninitialized value in hash element at /usr/sbin/btrbk line 879, <FILE> line 95.
    at /usr/sbin/btrbk line 103, <FILE> line 95.
	main::__ANON__("Use of uninitialized value in hash element at /usr/sbin/btrbk"...) called at /usr/sbin/btrbk line 879
	main::btr_tree(HASH(0x2b9c100)) called at /usr/sbin/btrbk line 909
	main::vinfo_subvol_list(HASH(0x2b9c100)) called at /usr/sbin/btrbk line 262
	main::vinfo_root(HASH(0x2b9c100)) called at /usr/sbin/btrbk line 1574

Is there any way to avoid this? --> Creating the snapshots, but only transfering if the destination path constains a btrfs-filesystem?

**Comment by digint** [comment]
This is a known bug in btrbk-0.17.0. **Please upgrade to v0.19.1**, your setup should work with this (note that the semantics have changed, use `snapshot_create always` instead of `snapshot_create_always yes`

If the snapshots are created on a daily basis (cron job or systemd timer unit) and you are running btrbk by hand whenever you attach the USB drive, I suggest a separate config for this:

##### /etc/btrbk/btrbk-manual.conf:
```
snapshot_dir btrbk_snapshots
snapshot_create no
resume_missing yes

volume /mnt/btrfs_pool
  subvolume @home
    target send-receive    /mnt/btrfs_bkp
```
Executing `btrbk -c /etc/btrbk/btrbk-manual.conf run` will then simply resume the missing snapshots from `/mnt/btrfs_pool/btrbk_snapshots/` (created by the cron job), without creating an additional snapshot.
