### ISSUE TITLE
btrbk produced an invalid snapshot

### ISSUE THREAD

**Issue by leezu** [digint/btrbk#251]
I keep snapshots obtained from my laptop and received over an ssh tunnelled btrfs send / receive at `/media/btrfs-top/_btrbk_backups/leonard-xps13`. I tried `btrbk archive /media/btrfs-top/_btrbk_backups/ /mnt/_btrbk_backups/` to copy all snapshots to an external disk mounted at `/mnt`.
This fails due some inconsistency in a snapshot:

```
WARNING: [send/receive] (send=/media/btrfs-top/_btrbk_backups/leonard-xps13/@home.20171001T0001, receive=/mnt/_btrbk_backups/le
onard-xps13) At subvol /media/btrfs-top/_btrbk_backups/leonard-xps13/@home.20171001T0001
ERROR: chown o629958-4676371-0 failed: No such file or directory
WARNING: [send/receive] (send=/media/btrfs-top/_btrbk_backups/leonard-xps13/@home.20171001T0001, receive=/mnt/_btrbk_backups/le
onard-xps13) At snapshot @home.20171001T0001
ERROR: Failed to send/receive btrfs subvolume: /media/btrfs-top/_btrbk_backups/leonard-xps13/@home.20171001T0001 [/media/btrfs-
top/_btrbk_backups/leonard-xps13/@home.20170903T0538] -> /mnt/_btrbk_backups/leonard-xps13
[delete] options: commit-after
[delete] target: /mnt/_btrbk_backups/leonard-xps13/@home.20171001T0001
WARNING: Deleted partially received (garbled) subvolume: /mnt/_btrbk_backups/leonard-xps13/@home.20171001T0001
ERROR: Error while cloning, aborting
Archived 1/15 subvolumes
WARNING: Skipping archiving of "/media/btrfs-top/_btrbk_backups/leonard-xps13/": At least one target aborted earlier
```

I am not sure what is causing this issue and how to debug it.
Ideally btrbk should have detected a potential issue when transferring the snapshot in the first place, but this may also be problem with btrfs itself.

I run kernel 4.18.6 and believe the problem may be related to the [changes between 4.18.5 and 4.18.6](https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.6). This believe is due to the btrbk archive process also failing on 4.18.5 but with several error messages in `dmesg` related to certain things hanging for more than 120 seconds. Unfortunately I did not save the output, but upgraded to 4.18.6 instead after running a `btrfs scrub` on both the internal and external disks (ie. the source and target of the btrbk archive). No errors were found. There is no output in dmesg on 4.18.6.

Please let me know if you have any interest in debugging this further. I will keep the faulty snapshots around for a while, but start afresh with a new "root" snapshot obtained from the laptop.

I currently have the following snapshots:
```
@home.20170903T0538
@home.20171001T0001
@home.20171105T1050
@home.20171204T0006
@home.20180107T0000
@home.20180204T0025
@home.20180304T0000
@home.20180401T0000
@home.20180603T2121
@home.20180701T0000
@home.20180805T0936
@home.20180812T0000
@home.20180819T0000
@home.20180826T0555
@home.20180902T0045
```

**Comment by LollenJumplan** [comment]
Garbled subvolumes can be due to network connectivity loss (I suppose your laptop is connected through wifi, even turning your microwave on could be the cause of this) or also if your server was receiving a subvolume while the archival was in progress. For the first possible cause, you can try to run btrbk clean on the laptop before archiving, for the second cause you should make sure that no subvolumes are being received, for example remounting the backup FS (I call it /media/backup) to something else (here /mnt/backup):
```
umount /media/backup
mount <backup-FS-device> /mnt/backup
mount <archive-FS-device> /mnt/archive
btrbk archive /mnt/backup /mnt/archive
umount /mnt/backup
mount <backup-FS-device> /media/backup
```
Generally, I think the second solution is more general and better, because it scales better if you have many machines. It also makes sure that no new subvolumes are created while the archival is in progress, which could lead to issues AFAIK. If you have backup timers configured on your systems, AFAIK these will just fail while you archival is in progress.
Note that these are just some potential issues I am aware of, and this is not necessarily correct information since I am not a developer.

**Comment by leezu** [comment]
If the snapshot gets damaged during transfer, the snapshot metadata is left in an inconsistent state, which btrbk detects. btrbk then asks you to run `btrbk clean`. This seems rather to be a bug in the linux kernel code or btrfs-progs. I close the issue for now.

**Comment by digint** [comment]
(sorry for the late answer, I kind of missed this one...)

> `ERROR: chown o629958-4676371-0 failed: No such file or directory`

It's related/duplicate of #91, #223, #225 : upstream bug, nothing that can be fixed in btrbk.

Sadly these incremental send-stream bugs still remain in newer kernels...
