### ISSUE TITLE
Nested config override

### ISSUE THREAD

**Issue by eurodomenii** [digint/btrbk#276]
Overriding a “first-level” is straightforward, --override <config_option>=<value> , acccording to https://digint.ch/btrbk/doc/btrbk.1.html

But, trying to override snapshot_name ( nested inside subvolume), I got the following error: 

`root@# btrbk -c amelia_name_override.conf --override=snapshot_name=powerdns dryrun
ERROR: Option "snapshot_name" is only allowed in "subvolume" context in option "--override"`

Config file: 
```
cat amelia_name_override.conf
ssh_identity  /root/.ssh/id_rsa_amelia

snapshot_preserve_min   latest
snapshot_preserve       no

target_preserve_min     all
target_preserve         no

archive_preserve_min    latest
archive_preserve        no

# Backup to external disk as well as some remote host
volume ssh://amelia/ab/
    subvolume ssd2sata
        incremental yes
        snapshot_name lxc
        snapshot_create  always
        target send-receive    /abs/amelia

```

Thx!

**Comment by digint** [comment]
I see your use case here, you probably want some emergency snapshot with different naming.

Fixed in 206e706d85032bdeae0df1d6418c58f8c4d2406b

Note that overriding `snapshot_name` will change ALL snapshot names, which is fine for your config, but as soon as more than one `subvolume` is defined they will all get the same name resulting in `ERROR: Subvolume "/mnt/btr_pool/subvol1" and "/mnt/btr_pool/subvol2" will create same snapshot: /mnt/btr_pool/override_name`. Of course this can be avoided passing filter arguments, e.g.:
```
btrbk run /mnt/btr_pool/subvol1 --override=snapshot_name=override_name
```
