### ISSUE TITLE
Recommended snapshot location?

### ISSUE THREAD

**Issue by 1n5aN1aC** [digint/btrbk#283]
I'm wondering what the recommended location to store snapshots is, and why.

I was previously using snapper, but am interested in using btrbk both for automatic snapshotting, and for transferring to a backup server. Snapper stored it's snapshots in a .snapshots folder *within* the subvolume being backed up.

From reading btrbk documentation, it seems this is **not recommended**. I have seen some mention in btrbk documentation of creating a separate subvolume just to store snapshot links in. What advantages does this have?

My (current) Setup:
```
/mnt/data (Large multi-device volume for nearly everything important)
- Pictures (subvolume)
\- .snapshots (storage for snapshots)
- Videos (subvolume)
\- .snapshots (storage for snapshots)
- Documents (subvolume)
\- .snapshots (storage for snapshots)
- Share (subvolume)
\- .snapshots (storage for snapshots)
```

**Comment by digint** [comment]
It does not matter much, this is up to you.

Hints:
 - Creating snapshots *within* the source subvolume (the snapper way) sounds terribly wrong, as the source tree is altered when doing backups. One can argue that snapshots are not "real" files, but from the user perspective they are.

- Creating a separate directory/subvolume for the snapshots has the advantage that you can set access permissions: Usually backups should not be readable by the user.

 - Creating a separate ".snapshots" subvolume (instead of directory) adds some structure to your filesystem, e.g. when listing subvolumes `btrfs sub list`. Also you can mount it somewhere (-o subvolid=xxx), but I don't see any use case why anyone would want that.

 - Creating a separate ".snapshots" subvolume (instead of directory) adds some overhead to the btrfs tree, making btrfs potentially slower (but probably has no real impact).

**Comment by 1n5aN1aC** [comment]
Alright, thanks very much, that makes sense!

**Comment by Gatak** [comment]
I have my volumes set up like this:

```
/mnt/rootvol
->snapshots/
->volume/
/mnt/storagevol
->snapshots
->volume
```
This makes it easy to know what is what. Also this means no nested subvols, even if they can be mounted in nested folders. for example in **/mnt/rootvol/volume/** `var/`, `var_db/`, `var_log/`, `www/`.

Mount command is easy to remember too. `mount ... -o subvol=volume/var`

Snapshots are then scheduled with btrbk and end up like this

```
drwxr-xr-x 1 root   root    118 May  6 12:43 var.20190615T0800/
drwxr-xr-x 1 root   root    104 Jun  9 10:15 var_db.20190610T0000/
drwxr-xr-x 1 root   root    104 Jun  9 10:15 var_db.20190611T0000/
drwxr-xr-x 1 root   root    104 Jun 11 10:03 var_db.20190612T0000/
drwxr-xr-x 1 root   root    104 Jun 12 15:28 var_db.20190613T0000/
drwxr-xr-x 1 root   root    104 Jun 13 18:18 var_db.20190614T0000/
drwxr-xr-x 1 root   root    104 Jun 14 13:07 var_db.20190615T0000/
drwxr-xr-x 1 root   root    104 Jun 14 13:07 var_db.20190615T0700/
drwxr-xr-x 1 root   root    104 Jun 14 13:07 var_db.20190615T0800/
drwxr-xr-x 1 root   root   3078 Jun  9 03:17 var_log.20190610T0000/
drwxr-xr-x 1 root   root   3078 Jun  9 03:17 var_log.20190611T0000/
drwxr-xr-x 1 root   root   3078 Jun 11 03:09 var_log.20190612T0000/
drwxr-xr-x 1 root   root   3078 Jun 12 22:31 var_log.20190613T0000/
drwxr-xr-x 1 root   root   3078 Jun 12 22:31 var_log.20190614T0000/
drwxr-xr-x 1 root   root   3078 Jun 12 22:31 var_log.20190615T0000/
drwxr-xr-x 1 root   root   3078 Jun 12 22:31 var_log.20190615T0700/
drwxr-xr-x 1 root   root   3078 Jun 12 22:31 var_log.20190615T0800/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190610T0100/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190611T0200/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190612T0000/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190613T0300/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T0800/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T1200/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T1400/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T1600/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T1700/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T1800/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190614T2300/
drwxr-xr-x 1 apache apache  104 Jun  6 04:10 www.20190615T0300/
```


I use two different btrbk configs. One for snapshots with unlimited retention and another for transferring snapshots to a backup device, as well as clearing old snapshots. This way no snapshots are removed if the backup  volumes/network, etc, is unavailable.

**Comment by Massimo-B** [comment]
Hi, I had similar ideas.
My early setups had nested subvolumes in /root just to exclude /var/tmp and stuff from snapshots. Then I changed this all to 2nd level subvolumes now (1 level under top-level) for easier migration to a new btrfs without re-creating all nested subvolumes.
Now instead of excluding from snapshots I wanted to have at least 1 or 2 snapshots from these non-important subvolumes. So my current setup from top-lvl view is like this:
```
/mnt/btrfs-top-lvl/
├── data
├── home
├── @root
│   ├── usr.portage
│   ├── usr.src
│   ├── var.cache
│   ├── var.db.repos
│   ├── var.lib.layman
│   └── var.tmp
├── root
├── snapshots
│   ├── data
│   │   ├── data.20190708T154800+0200
│   │   └── data.20190709T105117+0200
│   ├── home
│   │   ├── home.20190605T143320+0200
│   │   ├── home.20190707T050000+0200
│   │   ├── home.20190708T124318+0200
│   │   ├── home.20190708T154800+0200
│   │   ├── home.20190709T050000+0200
│   │   └── home.20190709T105117+0200
│   ├── @root
│   │   ├── usr.portage.20190617T135325+0200
│   │   ├── usr.portage.20190709T105117+0200
│   │   ├── usr.src.20190617T135325+0200
│   │   ├── usr.src.20190709T105117+0200
│   │   ├── var.cache.20190627T082601+0200
│   │   ├── var.cache.20190708T124318+0200
│   │   ├── var.cache.20190709T105117+0200
│   │   ├── var.db.repos.20190617T135325+0200
│   │   ├── var.db.repos.20190709T105117+0200
│   │   ├── var.lib.layman.20190617T135325+0200
│   │   ├── var.lib.layman.20190709T105117+0200
│   │   ├── var.tmp.20190617T135325+0200
│   │   └── var.tmp.20190709T105117+0200
│   ├── root
│   │   ├── root.20190605T143320+0200
│   │   ├── root.20190707T050000+0200
│   │   ├── root.20190708T124318+0200
│   │   ├── root.20190708T154800+0200
│   │   ├── root.20190709T050000+0200
│   │   └── root.20190709T105117+0200
│   └── virt
│       └── VirtualMachines.20190617T131445+0200
└── virt                # VirtualMachines, mounted with nodatacow
```
The reason for grouping all subvolumes that are mounted under root in the directory @root is that I can have a generic snapshot section without mentioning every single subvolume:

My complete btrbk.conf:
```
archive_preserve        12m 10y
archive_preserve_min    latest
incremental             yes
lockfile                /var/log/btrbk.lock
stream_buffer           3%
timestamp_format        long-iso
transaction_log         /var/log/btrbk.log

volume /mnt/btrfs-top-lvl/
    snapshot_create  onchange

    subvolume root
        group all,default,root
        snapshot_dir            snapshots/root
        snapshot_preserve_min   5d
        snapshot_preserve       2d 1w 1m
        target send-receive     /mnt/usb/data/snapshots/root
            group usbdata
            target_preserve_min     latest
            target_preserve         1d 4w 2m 1y
        target send-receive     /mnt/usb/mobiledata/snapshots/gentoo-mb/root
            group mobiledata
            target_preserve_min     latest
            target_preserve         1d 4w 2m 1y
    
    subvolume home
        group all,default,home
        snapshot_dir            snapshots/home
        snapshot_preserve_min   3d
        snapshot_preserve       4d 4w 2m 1y
        target send-receive     /mnt/usb/data/snapshots/home
            group usbdata
            target_preserve_min     3d
            target_preserve         6d 8w 6m 4y
        target send-receive     /mnt/usb/mobiledata/snapshots/gentoo-mb/home
            group mobiledata
            target_preserve_min     3d
            target_preserve         6d 8w 6m 4y
        
    subvolume data
        group all,default,data
        snapshot_dir            snapshots/data
        snapshot_preserve_min   latest
        snapshot_preserve       1w
        target send-receive     /mnt/usb/data/snapshots/data
            group usbdata
            target_preserve_min     latest
            target_preserve         2m
        target send-receive     /mnt/usb/mobiledata/snapshots/gentoo-mb/data
            group mobiledata
            target_preserve_min     latest
            target_preserve         2m
            
    subvolume VirtualMachines
        group all,vms
        snapshot_dir            snapshots/VirtualMachines
        snapshot_preserve_min   latest
        snapshot_preserve       2m
        #target send-receive     /mnt/usb/data/snapshots/VirtualMachines
            group usbdata
            target_preserve_min     latest
            target_preserve         2m
        target send-receive     /mnt/usb/mobiledata/snapshots/gentoo-mb/VirtualMachines
            group mobiledata
            target_preserve_min     latest
            target_preserve         2m
            
    subvolume @root/*
        group all,root
        snapshot_dir            snapshots/@root
        snapshot_preserve_min   latest
        snapshot_preserve       1m
        target send-receive     /mnt/usb/data/snapshots/@root
            group usbdata
            target_preserve_min     latest
            target_preserve         1d
        target send-receive     /mnt/usb/mobiledata/snapshots/gentoo-mb/@root
            group mobiledata
            target_preserve_min     latest
            target_preserve         1d
```
However I'm still not happy with that setup, as migration to a new btrfs should be as simple as...
```
for sub in /mnt/btrfs-top-lvl/snapshots/*; do btrfs send ...
```
So I consider having all snapshots in a plain directory. But this is not possible because btrbk creates snapshot-subdirectories for each subvolume section. I know there is btrbk archive to copy all snapshots to a new btrfs. I have used that for my last migration. But actually I would only need the last snapshot of each subvolume.

@digint , would it be possible to create a symlink or rather another snapshot with postfix 'last' instead of the timestamp that always contains the last snapshot of each subvolume?
Like /mnt/btrfs-top-lvl/snapshots/root/root.20190709T105117+0200/ getting another identical snapshot /mnt/btrfs-top-lvl/snapshots/root/root.last/ ?

Thinking further that could ease the btrfs send by sending
/mnt/btrfs-top-lvl/snapshots/*/*.last/

But I would then need a separate btrbk section for each single subvolume, at least if I don't want to have one section for all subvolumes. Any idea? Any comments?

**Comment by Gatak** [comment]
>  would it be possible to create a symlink or rather another snapshot with postfix 'last' instead of the timestamp that always contains the last snapshot of each subvolume?

I like this idea, so I put this as new feature request :) #287

**Comment by laundmo** [comment]
@digint I'm curious about your first and second points:

> Creating snapshots within the source subvolume (the snapper way) sounds terribly wrong, as the source tree is altered when doing backups. One can argue that snapshots are not "real" files, but from the user perspective they are.

> Creating a separate directory/subvolume for the snapshots has the advantage that you can set access permissions: Usually backups should not be readable by the user.

why are they not 'real files' that a use might want to access? Sure, they should be readonly, but beyond that?

A common usecase is needing to get back a file you've accidentally deleted/overwrote, which a subdirectory of the subvolume makes simple:
1. go to the .snapshots/ subdirectory
2. browse throug the timestamped snapshots to find the version you want to restore
3. copy the file(s) out

To me, this makes a lot of sense as a workflow, and i would wager its why snapper works the way it does (tho i dont know). I'd be curious if theres any subtleties or side effects i'm missing.
