### ISSUE TITLE
check for concurrent btrbk on remote host

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#305]
This is an idea for an enhancement.

I recently accidentally ran btrbk on 2 hosts at the same, each were sending backups to the same third remote host. I wish btrbk could try to detect this and throw an error.

**Comment by digint** [comment]
From your post I assume that running btrbk at the same time did work correctly, but what you are looking for is some functionality to manage the system load on your remote host (if not, this would be an upstream bug).

What you are looking for is some kind of remote lock, implementing this within btrbk is probably not that simple, as btrbk will also have to handle stale locks, and users might have different expectations for this (e.g. throw an error if lock is taken, or wait until lock is released).

A simple approach would be to add this in `authorized_keys`, something like this should work:

 - if you are using ssh_filter_btrbk.sh:
   `command="flock -n -E 255 /var/run/btrbk.lock ssh_filter_btrbk.sh [...]"`
 - else:
   `command="flock -n -E 255 /var/run/btrbk.lock $SSH_ORIGINAL_COMMAND"`

Instead of `flock -n` you can use `flock -w 60` to wait for 60 seconds if lock is taken.

**Comment by ian-kelling** [comment]
Thanks, this will work.
