### ISSUE TITLE
btrbk_verify does not work with ssh_filter_btrbk.sh

### ISSUE THREAD

**Issue by raumi75** [digint/btrbk#351]
My setup:

- A server with btrbk snapshots with root access limited by `ssh_filter_btrbk.sh`
- A offsite backup-device running btrbk pulling the snapshots over ssh.

If I run `btrbk-verify latest` on the offsite backup-device, `ssh_filter_btrbk.sh` rejects the command

```
Comparing [rsync] myservername:/mnt/btrfs_ssd/_btrbk_snap/@.20201114T1850 /mnt/raid_backup/_btrbk/@.20201114T1850
ERROR: ssh_filter_btrbk.sh: ssh command rejected: disallowed command (restrict-path: "/mnt/btrfs_ssd"): rsync --server --sender -nlHogDtpAXrce.iLsfxC --numeric-ids . /mnt/btrfs_ssd/_btrbk_snap/@.20201114T1850/
```

If I disable ssh_filter_btrbk.sh on my server, it works fine.

**Comment by digint** [comment]
btrbk-verify uses `rsync`, which really needs root on the target (well as soon as there is one file that the ssh user cannot access, meaning that it e.g. works without root for /home/myuser).

Hardening this with ssh_filter_btrbk.sh is almost impossible I'm afraid.

That's why you can run `btrbk-verify --ssh-user USER --ssh-identity FILE` which will override the settings from btrbk and use USER instead.

**Comment by raumi75** [comment]
I see. Thank you for the quick reply. I was hoping you could add rsync to the allowed commands.
