### ISSUE TITLE
No apparent support for spaces in subvolume declaration

### ISSUE THREAD

**Issue by TH3L0N3WOLF** [digint/btrbk#38]
Running version 0.19.3, attempting to declare subvolumes like "VirtualBox VMs", "BitTorrent Sync", etc. in the config returns "Ambiguous file for option "subvolume""

I tried using double and single quotes, as well as "\" to escape the space, and \040, of which none appeared to work.

**Comment by digint** [comment]
Yes, this is on puropse. From the man-page:

>  Note  that  btrfs is very picky on file names (mainly for security reasons), only the characters **[0-9] [a-z] [A-Z] and "._+-@"** are allowed.

If you are brave, change the according line in btrbk:

```perl
110: my $file_match = qr/[0-9a-zA-Z_@\+\-\.\/]+/;
```

You might run into trouble when allowing whitespace characters. This is *always* a pain to handle correctly with all those external tools needing special care on escaping special characters. This will probably never be implemented in btrbk.

As a general rule of thumb, I'd NEVER use special characters on the file/folder names, sooner or later there's a tool that does not handle it correctly. Use underscore `_` character instead of spaces.

**Comment by digint** [comment]
As a workaround, you could make a symlink to those subvolumes, and specify the symlink in btrbk.conf.

**Comment by TH3L0N3WOLF** [comment]
Oh okay. 
I kept spaces in certain folders (namely those mentioned above) because they came like that as a default. I didn't think much of it.
I went ahead and symlinked both to another location and it works perfectly, thanks.

**Comment by digint** [comment]
This is all well-documented in btrbk-0.21.0, closing issue
