### ISSUE TITLE
Troubles configuring root backup on Fedora

### ISSUE THREAD

**Issue by lzap** [digint/btrbk#384]
Hey,

I am very new to BTRFS and BTRBK. I have recently reinstalled my Fedora deployment to make use of BTRFS, the installer however configured it like this:

```
[root@nuc backups-btrfs]# mount | grep btrfs
/dev/sda5 on / type btrfs (rw,noatime,seclabel,ssd,space_cache,subvolid=256,subvol=/root)

[root@nuc backups-btrfs]# btrfs subvolume list /
ID 256 gen 261954 top level 5 path root
```

The ID is set to 256 instead of 5. I mounted a BTRFS-formatted USB HDD as `/mnt/backups-btrfs` and here is my configuration:

```
snapshot_preserve_min      2d
snapshot_preserve          3d
target_preserve_min        no
target_preserve            13d 7w 11m
archive_preserve_min       latest
archive_preserve           4y

volume /
  snapshot_dir btrbk_snap
  snapshot_create ondemand
  target /mnt/backups-btrfs/btrbk-root
  subvolume root
```

I created both `/btrbk_snap` and `/mnt/backups-btrfs/btrbk-root` directories. Dry run works fine:

```
# btrbk -v dryrun
btrbk command line client, version 0.28.3  (Wed Apr 28 08:56:03 2021)
Using configuration: /etc/btrbk/btrbk.conf
Creating subvolume snapshot for: //root
[snapshot] source: //root
[snapshot] target: /btrbk_snap/root.20210428
Checking for missing backups of subvolume "//root" in "/mnt/backups-btrfs/btrbk-root/"
Creating subvolume backup (send-receive) for: /btrbk_snap/root.20210428
No common parent subvolume present, creating full backup...
[send/receive] target: /mnt/backups-btrfs/btrbk-root/root.20210428
[send/receive] source: /btrbk_snap/root.20210428
[send/receive] (dryrun, skip) checking target metadata: /mnt/backups-btrfs/btrbk-root/root.20210428
Created 1/1 missing backups
Cleaning backups of subvolume "//root": /mnt/backups-btrfs/btrbk-root/root.*
Deleted 0 subvolumes in: /mnt/backups-btrfs/btrbk-root/root.*
Cleaning snapshots: /btrbk_snap/root.*
Deleted 0 subvolumes in: /btrbk_snap/root.*
Completed within: 0s  (Wed Apr 28 08:56:03 2021)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.28.3)

    Date:   Wed Apr 28 08:56:03 2021
    Config: /etc/btrbk/btrbk.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
//root
+++ /btrbk_snap/root.20210428
*** /mnt/backups-btrfs/btrbk-root/root.20210428

NOTE: Dryrun was active, none of the operations above were actually executed!
```

However I am running into issue when I attempt to execute normally:

```
# btrbk -v run
btrbk command line client, version 0.28.3  (Wed Apr 28 08:56:53 2021)
Using configuration: /etc/btrbk/btrbk.conf
Using transaction log: /var/log/btrbk.log
Creating subvolume snapshot for: //root
[snapshot] source: //root
[snapshot] target: /btrbk_snap/root.20210428
ERROR: Not a Btrfs subvolume: Invalid argument
ERROR: Failed to create btrfs subvolume snapshot: //root -> /btrbk_snap/root.20210428
WARNING: Skipping subvolume section: Failed to create snapshot: //root -> /btrbk_snap/root.20210428
Completed within: 0s  (Wed Apr 28 08:56:53 2021)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.28.3)

    Date:   Wed Apr 28 08:56:53 2021
    Config: /etc/btrbk/btrbk.conf

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
//root
!!! Aborted: Failed to create snapshot: //root -> /btrbk_snap/root.20210428

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.
```

Any advice?

```
# btrbk --version
btrbk command line client, version 0.28.3
```

Thanks.

**Comment by cmurf** [comment]
Could you attach /etc/btrbk/btrbk.conf ?
I think btrbk expects path to the subvolume being snapshot, which for Fedora default installation a subvolume named "root" is mounted at `/` - therefore path to the subvolume is `/` not `/root/`

The gotcha with putting snapshots into `btrbk_snap` is that means in effect they're nested inside the "root" subvolume. This isn't inherently bad, but it might get confusing if, for example you need to do a rollback. Since snapshots aren't recursive (they stop at subvolume boundaries), a rollback to a snapshot of "root" won't contain your backups, and then btrbk fails without making some sort of adjustment. (There's recursive snapshot support in libbtrfsutil.)

I think the immediate work around is to snapshot either `/` or mount the top-level of the file system somewhere. I'm not sure the best practice but let's call it `/run/toplevel. You can use fstab to do that for you every boot so that it's always ready.

In the usual case of default Fedora, the default subvolume is the mkfs default of ID 5. Therefore if you merely `mount /dev/sdXY /run/toplevel` you get ID 5 mounted there, and inside you'll see the installer created "root" and "home" subvolumes. I'm going to skip discussion of the non-usual case where something (e.g. snapper) has taken control of the default subvolume.

If you configuration expects snapshot source `/run/toplevel/root` and snapshot target `/run/toplevel/snapshots` now the snapshots are no longer placed in the "root" suvolume, and any rollback is a bit more organized, but totally optional.

Longer term, maybe developers will take interest in libbtrfsutil. Both the C API and Python bindings have file descriptor variants to create/destroy subvolumes and snapshots without a path. And to do so in their own namespace to keep it all self-contained, without either needing the top-level persistently mounted, or putting snapshots in active search paths where they end up messing up common tools like find, locate, and du. Btrbk might want a way to specify the "default subvolume" as backup source, because it could be changing on a semi-regular basis due to a snapshot/rollback regime.

**Comment by lzap** [comment]
Sure.

```
preserve_day_of_week       monday

snapshot_preserve_min      2d
snapshot_preserve          3d
target_preserve_min        no
target_preserve            13d 7w 11m
archive_preserve_min       latest
archive_preserve           4y

volume /
  snapshot_dir btrbk_snap
  snapshot_create ondemand
  target /mnt/backups-btrfs/btrbk-root
  subvolume root
```

**Comment by lzap** [comment]
Nope, I am still waiting for advice. I am without backups of the root volume for the whole time :-)

Anything I can test? I do not understand btrfs very much, just migrated from xfs...

**Comment by cmurf** [comment]
It sounds like a downstream issue? In which case we should discuss it on the [Fedora devel@](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/) mailing list, and come to a consensus on what should be done within Fedora's default btrbk configuration or documentation. It'd also be appropriate to file an RFE (request for enhancement) against btrbk using the [Fedora bug tracker](https://bugzilla.redhat.com/) but I think more comes from the discussion in devel@ rather than only bugging @xenithorb

**Comment by bdaase** [comment]
@cmurf Unfortunately it looks like btrbk is practically dead in Fedora. No updates (except releng) since more than two years....

**Comment by lzap** [comment]
Oh right, since I am fedora packager, I will look into this:

https://src.fedoraproject.org/rpms/btrbk/pull-requests

Contacted the maintainer, will offer him help or poke him to start merging stuff.

@cmurf the Fedora package does not seem modify anything, it ships the default configuration unchanged, I am not sure what exactly is your point.

So I have updated to 0.31.3 and trying again. Here is my config:

```
transaction_log            /var/log/btrbk.log
stream_buffer              512m

snapshot_preserve_min      2d
snapshot_preserve          3d
target_preserve_min        no
target_preserve            13d 7w 11m
archive_preserve_min       latest
archive_preserve           4y

volume /
  snapshot_dir btrbk_snap
  snapshot_create ondemand
  target /mnt/backups-btrfs/btrbk-root
  subvolume root
```

Now it looks promising:

```
$ sudo btrbk -v dryrun
btrbk command line client, version 0.31.3  (Mon Jan 10 14:48:31 2022)
Using configuration: /etc/btrbk/btrbk.conf
Creating subvolume snapshot for: /root
[snapshot] source: /root
[snapshot] target: /btrbk_snap/root.20220110
Checking for missing backups of subvolume "/root" in "/mnt/backups-btrfs/btrbk-root/"
No common parent subvolume present, creating non-incremental backup...
[send/receive] target: /mnt/backups-btrfs/btrbk-root/root.20220110
[send/receive] source: /btrbk_snap/root.20220110
[send/receive] (dryrun, skip) checking target metadata: /mnt/backups-btrfs/btrbk-root/root.20220110
Created 1/1 missing backups
Cleaning backups of subvolume "/root": /mnt/backups-btrfs/btrbk-root/root.*
Deleted 0 subvolumes in: /mnt/backups-btrfs/btrbk-root/root.*
Cleaning snapshots: /btrbk_snap/root.*
Deleted 0 subvolumes in: /btrbk_snap/root.*
Completed within: 1s  (Mon Jan 10 14:48:32 2022)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.31.3)

    Date:   Mon Jan 10 14:48:31 2022
    Config: /etc/btrbk/btrbk.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
/root
+++ /btrbk_snap/root.20220110
*** /mnt/backups-btrfs/btrbk-root/root.20220110

NOTE: Dryrun was active, none of the operations above were actually executed!
```

Can you confirm this looks clean for my case? In case of Fedora I have:

```
/dev/sda5 on / type btrfs (rw,noatime,seclabel,ssd,space_cache,subvolid=256,subvol=/root)
/dev/sdb1 on /home type btrfs (rw,noatime,seclabel,ssd,space_cache,subvolid=5,subvol=/)
```

Thanks!

**Comment by lzap** [comment]
Hey, for the record: we have fixed the Fedora package, Fedora Rawhide already contains the latest version.

**Comment by onnonym** [comment]
I am also on fedora and ran into the same problem, independent of the btrbk version.

What worked was replacing:
 subvolume root

with
  subvolume .
  snapshot_name rootfs

Source: https://wiki.calculate-linux.org/btrbk
