### ISSUE TITLE
Preserving a total number of snapshots regardless of age

### ISSUE THREAD

**Issue by KodyVB** [digint/btrbk#388]
Sorry if this has been answered before, but I went through 4-5 pages of issues looking for it and couldn't find anything in the documentation regarding it.

Is there a way to set the snapshot_preserve or snapshot_preserve_min to be a total number of snapshots, instead of a time-based argument? I'd like to be able to have the latest X amount of snapshots, regardless of if that spans months or a single day.

**Comment by digint** [comment]
It's not possible to restrict to a "total number of backups" (which ones should they be? the last x backups?).

What you can do instead is control the rate of running btrbk, and set `snapshot_preserve_min no` (default).

**Comment by KodyVB** [comment]
I see, I was hoping to be able to be able to restrict to the newest X number of backups. A first-in first-out type of approach that cares about the total number of snapshots, rather than how many snapshots are in the hourly, daily, etc. categories. I had been working on some [pacman hooks and logging scripts](https://gitlab.com/KodyVB/btrbk-pac) so that btrbk would be used before and after pacman transactions, as well as the affected packages being logged.

Since this use case wouldn't be periodic, like running btrbk on a cron job would be, I thought it would be better to have the latest X number of snapshots preserved, rather than using the time category based solutions. This is especially the case since pre- and post-transaction snapshots usually happen within minutes of each other at the slowest, or more often within seconds of each other. So if I could set up btrbk to keep the latest 40 snapshots regardless of their frequency, that could mean I could have them spanning months if I hardly use pacman or just a few hours if I was downloading things more frequently.

**Comment by digint** [comment]
Note that creating many snapshots is usually not a problem and will not dramatically increase disk usage, unless:
 - you have many frequent additions+deletions
 - the number of snapshots does not go into thousands.

The problem with your approach (keep 40 latest snapshots) is that if you start play around with pacman (using your hooks) and run it 40 times doing some experiments / whatever, you will loose the backup from yesterday, which you probably rely on if something goes wrong. Having a schedule based on time limits is usually a better option.

**Comment by Rohrschacht** [comment]
I do believe there is a legitimate use case for this. I understand your example of creating too many snapshots in a short amount of time and rotating them out too quickly. However, let's look at the same issue from the other side.

Let's say I update my OS about once a week and run btrbk before that by hand. Because I might not catch a problem immediately, I would like to keep the snapshots for about 8 weeks. Easily achievable with:
```
snapshot_preserve 8w
```

But now let's say I am suddenly unable to use the computer for 6 months. The next time I use it, I want to update it and take a snapshot before. Since all other snapshots would now be considered too old, they would all get deleted, keeping only the one I just created. If there was a problem introduced a couple of updates ago, I wouldn't be able to roll back, because I just lost all my snapshots.

You might say I could mitigate this by also keeping monthly snapshots like this:
```
snapshot_preserve 8w 6m
```
But that would mean that I have to anticipate that I might not be able to use my computer for that half a year. And also, if everything is "normal" and I am using it regularly, I wouldn't need the monthly snapshots. They would only begin to take up space on my small laptop ssd.

However, this problem could be easily mitigated if I could do something like this:
```
snapshot_preserve 8w
snapshot_preserve_min 5
or
snapshot_preserve_min 5n
or
snapshot_preserve_min latest+4
```
That way, when I use btrbk again after a long time, I could do so without worrying about it. I would know that some of my old snapshots would be kept for me, even though they would be considered too old because they are older than 8 weeks.

**Comment by peterhoeg** [comment]
I don't need to snapshot `/` as it can be trivially rebuilt and as a consequence I only care about `/home` *and* all runs are done via a timer, so I'm never to going to trigger it manually and thus "run out" of snapshots. 
But a device might easily be off for a few days and that basically destroys all my hourly snapshots that I keep for 48 hours on the next run after starting it.
I would *very* much like the option of keeping snapshots based on count rather than time.

**Comment by ds4l** [comment]
In my opinion this is a crucial feature for using btrbk on personal computers. These are not running 24/7 or are switched on and off quite irregularly. I would really appreciate an option as proposed by the previous posters.

**Comment by ldpercy** [comment]
I'd also like to request this as a feature, if it's not too hard to implement.

I tend to use btrbk on an as-needed basis and use the the schedule for the backup targets, but would prefer to able to keep the last 2 or 3 snapshots locally for reference.

**Comment by FireAcidCow** [comment]
I would also like this feature, as I am looking to use this as a game folder backup, and I want to keep the last ten or so saves as well as all the saves within the past week. Currently looking for some other software that fits my current needs, but it would be nice to have it here since it's specifically for btrfs
