### ISSUE TITLE
ssh-agent identities and "no SSH identity provided"

### ISSUE THREAD

**Issue by wolfgangrupprecht** [digint/btrbk#482]
When using ssh identities and keys stored in the ssh-agent btrbk has no problem logging in and getting the remote snapshots yet the warning still gets printed.

WARNING: No SSH identity provided (option ssh_identity is not set) for: ssh://example/mnt/btr_pool/root

Perhaps the warning could be stored and only printed if the ssh fails?

**Comment by digint** [comment]
Thanks for reporting!

The idea behind this warning was to simplify first steps, as most users would probably want to set `ssh_identity`. As it is not required, warning on every run is simply wrong, so I turned it into a hint displayed along with SSH errors:

```
(note: option "ssh_identity" is not set, using ssh defaults)
```
 
fixed in cf2065df308d81f5503d3dc0f0c96cd09d7b9de7, along with some other SSH related improvements I had lying around:
 - allow disabling ssh_identity and ssh_user options
 - tidy btrbk.conf.example
