### ISSUE TITLE
Feature request: Automatically remove stray subvolumes

### ISSUE THREAD

**Issue by LollenJumplan** [digint/btrbk#61]
I recently installed this program on my laptop to create local "backups" in the form of snapshots and transfer them to my server if the server is reachable (via the "target"-option).
I also created systemd unit files and wrapper scripts to accomodate for shutdown etc.
So far it works great and I think this program was just what I was looking for, and I am thankful that someone took the time to write a piece of free softwarfor this.
But if the network connection is lost, there are these half-baked subvolumes left behind on the server, and on the next runs it just aborts because it finds "stray" subvolumes and doesn't know how to deal with them. What I would find great is an option (no default) to tell btrbk to just get rid of these stray subvolumes and start over. If I have overlooked something here, I am sorry, but I had a look at the manpages and FAQ before and didn't really find anything.

**Comment by digint** [comment]
Sadly there is no reliable way of identifying stray subvolumes, at least none that I know of (although btrfs is fast-moving, maybe I should re-check some day).

What btrbk does to avoid stray subvolumes is to run `btrfs subvolume delete` right after a failed `btrfs receive` operation. But this does not cover all error cases, e.g. by a broken link or by killing the btrbk process before completion.
This is already regarded as a "dirty hack", since (in my opinion) this issue should be fixed in btrfs-progs, assuring that a `btrfs receive` never leaves stray subvolumes behind. But this again is a complicated task, as `btrfs receive` does all its magic from userspace, and as far as I know there is no possibility to reliably rollback stuff there.

I already thought of some workarounds for this, but none of them is really satisfying: for example I could receive the stream to a temporary directory and move it into the correct place on success. This would help a bit, but still it would not be satisfying, as there would possibly be stray subvolumes in the temporary location. And then again, what happens if moving the subvolume fails?

So for now, until I can find a "real, easy and non-hacky" solution for this, I rather leave it to the sysadmin to delete stray subvolumes by hand than doing some magic here that possibly deletes too much.

**Comment by LollenJumplan** [comment]
What about creating some kind of file or folder that holds the names of all unfinished subvolumes, getting deleted/modified only after the subvolume has been transferred successfully? That would avoid the part of moving subvolumes around. And if it fails, on the next run it could maybe tell with a little more certainty and therefore maybe could (optionally) be a little more automatic about that.
(Optionally) moving from the temporary folder doesn't sound bad to me either, because btrbk could just delete everything in this folder on the next run, offering resilience against errors, and could guarantee that the target only holds valid backups one can restore from.
Also, the chance btrfs-progs detects a stray subvolume even though it is a valid one should be pretty low, shouldn't it? So maybe an option to still delete these on the next run could maybe be good, because either they are just, as expected, unfinished or corrupt backups, or they are valid, and then btrbk just retransfers them automatically (if they are not scheduled for removal anyway), right?
While I agree with your position that btrfs-progs just doesn't do the right thing here, and that this should be fixed there ultimately, I think it would still be great (in my opinion) to have something in the meantime that works around that, because it would make the program much more useful for people like me who don't watch log files too often, just want a "resilient" backup system and could easily overlook the fact that their new "backups" are not transferred to their target as expected ;)
I hope what I write doesn't sound like demanding or criticizing something or even complaining, because that's really not what I want to do here. I just want to provide some thougts from the user perspective :)

**Comment by LollenJumplan** [comment]
Just after I posted this I also visited the btrfs wiki where they have some design notes on send/recieve.
I noticed they have a point about deleting recieved subvolumes on error, but then again, it's in there for over 2 years now. But hey, at least they seem to be aware of it.

**Comment by digint** [comment]
I found a way to recognize incomplete backups: the `parent_uuid` flag is only set if a `btrfs receive` operation was successful, so I can check for this.

Right now I'm working on a patch that recognizes this, and takes actions accordingly (probably with a new config option for "auto-deletion"). This way I can keep btrbk stateless, which it would not be any more with the solutions proposed in this thread.

PS: sorry for the late answer, I was in vacation...

**Comment by LollenJumplan** [comment]
Great to hear from the project again, but there is nothing to apologise for since there werent any expectations (in a positive way, of course).
I'm looking forward to this feature, I think it's certainly worth the work there for some people (including me, of course).

**Comment by digint** [comment]
Added `btrbk clean` command, which deletes all the incomplete backups (use `btrbk -n clean`  for dry-run).

Add this to your wrapper scripts if you want it automated, e.g. before calling `btrbk run`.

Implemented in 3461f9440bbacb0017eadbe87adaaacd75160a09

**Comment by digint** [comment]
Implemented in btrbk v0.22.0
