### ISSUE TITLE
Wrong snapshot is sent when unable to back up for x amount of days.

### ISSUE THREAD

**Issue by TH3L0N3WOLF** [digint/btrbk#7]
I'm running BTRBK as a timer on a systemd-enabled system. I had my back up drive disconnected from my system for a couple of days, and I recently connected it today. Upon running btrbk, I took a look at the executed commands and found that it will attempt to send the first missed snapshot under the current day's name like so:
btrfs send -p /mnt/subvolroot/server/srv/gameservers/tekkit/backups/world.20150323 /mnt/subvolroot/server/srv/gameservers/tekkit/backups/world.20150326

Currently running BTRBK 0.14

**Comment by digint** [comment]
This is correct behaviour. Since you had your backup disk disconnected on the days 2015-03-24/25, the latest common snapshots were made on 2015-03-23, and btrbk makes an incremental send with the parent `-p .../world.20150323`.
Note that the parent snapshots for an incremental backup must always be present on both btrfs volumes, see https://btrfs.wiki.kernel.org/index.php/Incremental_Backup for details on this.

**Comment by TH3L0N3WOLF** [comment]
I sincerely apologize, I feel like an idiot for missing that. 
Upon closer inspection, the changes from the days in-between were logged, but in deeper directories. 
Sorry about that.
