### ISSUE TITLE
Allow wildcards on subvolume declaration

### ISSUE THREAD

**Issue by digint** [digint/btrbk#71]
Here's a question I got per mail:

> I use LXC containers and in my datapool btrfs volume I have an lxc subvolume with my containers. I'm now migrating to using btrfs 'properly' for containers and am specifying a btrfs backingstore when I create my containers. With this option, LXC creates a new subvolume for the rootfs of the new container. Therefore, my lxc subvolume has another subvolume for the containers.
> 
> Since btrfs snapshots don't capture the nested subvolumes, what's a strategy to automatically back up this new nested subvolume? Would it be possible for btrbk to have a yes/no option like "include_nested" to automatically capture the nested subvolumes and include them in the same directory structure in both the snapshots dir and target dir?

For now, you need to specify all the source subvolumes to be backed up in separate `subvolume <name>` statements. I already gave some thoughts to support nested subvolumes, or (even more powerful) wildcards, e.g. `subvolume *` or `subvolume lxc/*`. This will most certainly come some
day, I never came around to implement this (as it needs some changes in the btrbk data structures).

**Comment by digint** [comment]
implemented in: 247f023babaccee97247e17d19cbac1976d2b1fd (on the master branch, missing documentation).

Only asterisk `*` wildcard is supported.

You can use something like:
```
volume /my/volume
  subvolume *
  subvolume subdir/*
  subvolume *xxx*
```
Note that this is pretty dynamic, e.g. if you delete a previously used source subvolume by hand, btrbk will not be aware of the snapshots and targets any more, and thus never schedule/delete them.

Not yet thoroughly tested, but works fine for me.

**Comment by digint** [comment]
Implemented in [btrbk-v0.23.0-rc1](/digint/btrbk/releases/tag/v0.23.0-rc1) (a27f99af465f8d54eff5bc0b4161404ebabdeaa9)

Please read the [upgrade guide](https://digint.ch/btrbk/doc/archive/btrbk-0.23.0-rc1/upgrade_to_v0.23.0.html) before updating to v0.23.0.

**Comment by Anthony25** [comment]
Hello,
Wildcards are great, but about the mail you received, I am actually encountering the same issue with lxc: when lxc creates a container, it creates a directory having the same name as the container, with a configuration file inside and a btrfs subvolume named `rootfs`.
So it looks like this:
```
container_name
├── config
├── rootfs
└── container_name.log
```

The issue is that each subvolume to backup is named `rootfs`, so btrbk fails because a snapshot of 2 lxc containers will create in fact the same snapshot:
```
ERROR: Subvolume "/mnt/poolbtrfs/@lxc/vm-ampache-0/rootfs" and "/mnt/poolbtrfs/@lxc/vm-dl-0/rootfs" will create same snapshot: /mnt/poolbtrfs/@snapshots/rootfs
```

An `include_nested` option would solve the issue, as it would keep the same structure as the volume it snapshots, but this is already the goal of the archive option, right?
Otherwise, I do not really see how it could be done, but a kind of pattern for the `snapshot_name` would also do the trick.

For the moment, I can change each rootfs subvolume name to the container one.

**Comment by digint** [comment]
@Anthony25 thanks for reporting this.
I added new issue #127 (enhancement) to track this. I'm not sure how to solve this yet (and not much time atm), but should be fixed for wildcards to make sense for lxc containers.
