### ISSUE TITLE
Add lockfile support

### ISSUE THREAD

**Issue by digint** [digint/btrbk#81]
Add configuration option: `lockfile <file>`, and command line option `--lockfile`.

Solves concurrency (e.g. in cron jobs) when doing large, rate-limited transfers.

**Comment by GrahamCobb** [comment]
Yes, please!  I have just added flock locking to all my btrbk cron jobs because I have just started using backups (not just snapshots) and have hit this.

One idea I had, by the way, was to automatically use the config file for the lock (maybe with the lockfile option to allow it to be overriden if the config file is on a NFS disk or something).

**Comment by digint** [comment]
Implemented in e4a7ba4be5661471b55969f8c4eb115c81340c50, btrbk-v0.23.2
